//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covisky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boleto()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public decimal bol_ID_Reserva { get; set; }
        public decimal bol_No_Boleto { get; set; }
        public Nullable<decimal> bol_aero_ID_Origen { get; set; }
        public Nullable<decimal> bol_aero_ID_Destino { get; set; }
        public Nullable<System.DateTime> bol_Fecha_Salida { get; set; }
        public Nullable<System.DateTime> bol_Fecha_Regreso { get; set; }
        public Nullable<decimal> bol_cla_ID { get; set; }
        public string bol_pas_Pasaporte { get; set; }
        public Nullable<decimal> bol_cantidad_Pajaseros { get; set; }
        public Nullable<System.TimeSpan> bol_Hora_Salida { get; set; }
        public Nullable<System.TimeSpan> bol_Hora_Llegada { get; set; }
        public string bol_Aeroline { get; set; }
        public Nullable<decimal> bol_Costo { get; set; }
        public Nullable<decimal> bol_tar_NoTarjeta { get; set; }
        public Nullable<decimal> bol_ser_ID { get; set; }
        public Nullable<decimal> bol_Descuento_Millas { get; set; }
        public string bol_Escala { get; set; }
    
        public virtual Aeropuerto Aeropuerto { get; set; }
        public virtual Aeropuerto Aeropuerto1 { get; set; }
        public virtual Clase Clase { get; set; }
        public virtual Pasajero Pasajero { get; set; }
        public virtual Servicio_Extra Servicio_Extra { get; set; }
        public virtual Tarjeta Tarjeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
