//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covisky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Factura
    {
        public decimal des_fac_ID { get; set; }
        public Nullable<decimal> des_fac_No { get; set; }
        public string des_fac_Detalle { get; set; }
        public Nullable<decimal> des_fac_subTotal { get; set; }
    
        public virtual Factura Factura { get; set; }
    }
}
