//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covisky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasajero
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pasajero()
        {
            this.Boleto = new HashSet<Boleto>();
        }
    
        public decimal pas_ID { get; set; }
        public string pas_Pasaporte { get; set; }
        public string pas_Nombre { get; set; }
        public string pas_Apellido { get; set; }
        public Nullable<System.DateTime> pas_Fecha_Nac { get; set; }
        public string pas_correo { get; set; }
        public Nullable<decimal> pas_telefono { get; set; }
        public string pas_Prefijo { get; set; }
        public string pas_Direccion { get; set; }
        public Nullable<decimal> pas_tip_ID { get; set; }
        public Nullable<decimal> pas_No_Viajero_Fre { get; set; }
        public string pas_Nacionalidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleto> Boleto { get; set; }
        public virtual Tipo_Pasajero Tipo_Pasajero { get; set; }
    }
}
