//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covisky.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoviskyEntities : DbContext
    {
        public CoviskyEntities()
            : base("name=CoviskyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aeropuerto> Aeropuerto { get; set; }
        public virtual DbSet<Asiento> Asiento { get; set; }
        public virtual DbSet<Boleto> Boleto { get; set; }
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<Detalle_Factura> Detalle_Factura { get; set; }
        public virtual DbSet<Emisor_Tarjeta> Emisor_Tarjeta { get; set; }
        public virtual DbSet<Factura> Factura { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Pasajero> Pasajero { get; set; }
        public virtual DbSet<Servicio_Extra> Servicio_Extra { get; set; }
        public virtual DbSet<Tarjeta> Tarjeta { get; set; }
        public virtual DbSet<Tipo_Pasajero> Tipo_Pasajero { get; set; }
    }
}
