//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covisky.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarjeta()
        {
            this.Boleto = new HashSet<Boleto>();
        }
    
        public decimal tar_NoTarjeta { get; set; }
        public string tar_FechaExp { get; set; }
        public Nullable<decimal> tar_CodSeguridad { get; set; }
        public Nullable<decimal> tar_millas { get; set; }
        public Nullable<decimal> tar_et_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boleto> Boleto { get; set; }
        public virtual Emisor_Tarjeta Emisor_Tarjeta { get; set; }
    }
}
